### ISSUE TITLE
Create dataset loader for eDiseases

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#243]
## Adding a Dataset
- **Name:** eDiseases
- **Description:** *None provided*
- **Task:** SENT_CLASS|SENT_CLASS
- **Paper:** https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6264154/
- **Data:** https://zenodo.org/record/1479354#.Yhs0eBNueWg
- **License:** CC BY-NC 4.0

**Comment by mdmanurung** [comment]
Too bad that the authors did not include the actual posts that were labeled; these have to be scraped still.

**Comment by nadahlberg** [comment]
#self-assign

**Comment by nadahlberg** [comment]
@jason-fries working on a crawler for this now -- can I implement if able to collect the text?

**Comment by jason-fries** [comment]
@nadahlberg WOW! That would be incredible. If you can come up with a generic enough solution, maybe we could implement this into utils for similar datasets? Let us know how we can help !!

**Comment by hakunanatasha** [comment]
@nadahlberg let us know if we can help - this would be *amazing* ping us on discord or here.

**Comment by nadahlberg** [comment]
@jason-fries @hakunanatasha

Hi y'all, sorry for the delay on this.  Unfortunately the crawler definitely won't be general purpose at all.  There are some pretty tremendous quirks with this site that make it very clunky to crawl.  (most notably: comments lazy load, requiring scrolling down the page, but scrolling to the bottom lazy loads a redirect to a new post -- so we have to find the Goldilocks amount of scrolling to capture all the comments without triggering the redirect!)

I've had success getting the crawler working, however I think there is a larger issue with the original data.  The dataset includes both post-level data and the sentence segmentation span indexes for each sentence in the post.  But the sentence-level data appears to have incorrectly aligned post ids.  This is easier to show than explain, so please check out this colab where I compare the data we crawled for one page with the post/sentence data from the original dataset:
[https://colab.research.google.com/drive/1s-iH7CCptm3MdKzUVFYI9YXImt0wCGAP?usp=sharing](https://colab.research.google.com/drive/1s-iH7CCptm3MdKzUVFYI9YXImt0wCGAP?usp=sharing)

As you can see in the colab, there is an easy heuristic we could use to 'fix' the original data by correcting the post_ids on the sentence-level table.  But I wasn't sure how heavy-handed Huggingface wants to be in modifying/improving these datasets.  Is it worth continuing to pursue this?

It's worth mentioning that there will be other issues, so the question is do we want to publish a dataset that requires so many qualifications?

Other issues include:
- Some posts have been deleted since the original crawl (I have manually verified this in cases where it has cropped up).
- We don't have a perfectly unique way to match the posts we crawl to the original data (however using author, date, and length of text we can make an extremely reliable assumptions about when merging).
- Rarely, but sometimes, the text we crawl has slightly different lengths from the max end index in the original data (even if we fix the problem above).  I'm not sure why, perhaps these posts were edited since they were originally procured.  The difference is very minor (<10 characters) however this could lead us to improperly segmenting the sentences if we use the sentence indexes from the original data to chop the newly crawled text.

What do you think?

Thanks for any help!

**Comment by jason-fries** [comment]
@nadahlberg  Thanks for the incredible deep dive here. Sorry this dataset turned out to be so frustrating! 
Our goal for this version of the hackathon was to avoid "fixing" or otherwise cleaning datasets since one of the goals of this effort is to audit the state of biomedical data targeted for use in machine learning.

Since the original dataset has some pretty serious errors, let's just flag this dataset as problematic and not focus on implementing it. We'll mark this as completed (with credit to you of course!) but not merged.
