### ISSUE TITLE
Create dataset loader for PubMedQA

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#25]
From https://github.com/pubmedqa/pubmedqa

**Comment by nomisto** [comment]
Found here [https://huggingface.co/datasets/pubmed_qa](https://huggingface.co/datasets/pubmed_qa), however without official splits.

**Comment by SamuelCahyawijaya** [comment]
#self-assign

**Comment by hakunanatasha** [comment]
@nomisto good catch - i think we'll implement with official splits. There is a small amount of datasets currently overlapping with the original library.

@jason-fries @galtay @leonweber thoughts?

**Comment by hakunanatasha** [comment]
@SamuelCahyawijaya can you let us know if you still intend to work on this? We'd like to update our project board. Please let us know by **Friday, April 8**, so we can plan accordingly. You can ping me in a comment via @hakunanatasha or on Discord with @admins

**Comment by SamuelCahyawijaya** [comment]
@hakunanatasha : Yes, actually I am working on this one right now and I find a problem with the PQA-L(abelled) as the official split on the github link above is actually a 10-fold CV. Should I use only a single split or provide multiple configs for each fold?

**Comment by hakunanatasha** [comment]
Hi @SamuelCahyawijaya 

For multiple splits, I see the default approach

(1) Create a source/bigbio for the combined splits (so 1 train/dev set, I think)

(2) Create source/bigbio for each split individually

Bioasq may be a useful example
https://github.com/bigscience-workshop/biomedical/blob/0e35df219519fea9b14c58d26b6e26c81415160f/examples/bioasq.py#L494

**Comment by hakunanatasha** [comment]
Let me know if you need help : )

**Comment by hakunanatasha** [comment]
Also - I noticed you have a PR open for this, would you mind updating with the splits? I'll change the reqs at some point too.

**Comment by SamuelCahyawijaya** [comment]
@hakunanatasha : I see, noted, let me add the 10-fold split then 👍🏻

**Comment by sunnnymskang** [comment]
@SamuelCahyawijaya @galtay @hakunanatasha unit tests failing on bigbio_schema; please advise whether this is an unexpected behavior

**Comment by SamuelCahyawijaya** [comment]
Hi @sunnnymskang, just wondering whether it is caused by the datasets package version problem. Before we have a similar issue for `pqaa` and `pqau` data split which we have discussed [here](https://github.com/bigscience-workshop/biomedical/pull/357). 

We need to upgrade the dependency to `datasets>=2.0.0` since there is a `datasets` package bug with the google drive link download as mentioned [here](https://github.com/huggingface/datasets/pull/3787). Could you confirm that you tested using `datasets>=2.0.0`?

If the problem remains even with the correct `datasets` version, I can investigate further on this issue this Wednesday.

**Comment by hakunanatasha** [comment]
PubmedQA in dataloaders.
