### ISSUE TITLE
Create dataset loader for PMC-Patients

### ISSUE THREAD

**Issue by jason-fries** [bigscience-workshop/biomedical#258]
## Adding a Dataset
- **Name:** PMC-Patients
- **Description:** *None provided*
- **Task:** SENT_CLASS|STS|IR
- **Paper:** https://arxiv.org/abs/2202.13876
- **Data:** https://github.com/zhao-zy15/PMC-Patients/tree/master/datasets
- **License:** CC BY-NC-SA

**Comment by cakiki** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @cakiki  can you let us know if you are still working on this so we can update our project board? Please just notify us the status **by Friday April 8**.  You can response to this comment or ping us on Slack or Discord. 

No worries if you are not finished but still intend to work on this!

**Comment by cakiki** [comment]
Hi @jason-fries! I'm still working on all of my issues.

**Comment by shamikbose** [comment]
#self-assign

**Comment by jason-fries** [comment]
Hi @shamikbose 
Thanks for volunteering for this dataset! Let us know if we can help in anyway :)

**Comment by shamikbose** [comment]
Hi @jason-fries ! This is a very large dataset with a number of subsets for different tasks. I have a couple of questions:
1. Since the dataset is very large (~1.5GB), should there be a disclaimer? Not sure what's done in the case of datasets like that
2. This has a number of subsets for different tasks (Similarity measures, patient-article retrieval). Should they be different loaders where each dataloader uses a specific subset? They have the same link

**Comment by benjaminbeilharz** [comment]
#self-assign
