### ISSUE TITLE
Create a dataset loader for ESSAI 

### ISSUE THREAD

**Issue by hakunanatasha** [bigscience-workshop/biomedical#69]
From https://clementdalloux.fr/?page_id=28

**Comment by giganttheo** [comment]
#self-assign

**Comment by giganttheo** [comment]
Hi @hakunanatasha . I have a finished script for this task. Since the dataset also contains information for a POS-tagging task for which no bigbio schema is relevant, I suggested a new schema in a merge request (https://github.com/bigscience-workshop/biomedical/pull/366). If it is accepted I will add this new schema for this specific dataset. Otherwise I will also push my dataloading script for this dataset very soon :)

**Comment by giganttheo** [comment]
Also I think the "Brazilian Portuguese" tag is not relevant for this dataset since it contains only French text :)

**Comment by hakunanatasha** [comment]
@giganttheo lol, must have been a mistaken annotation on our part 😅

**Comment by hakunanatasha** [comment]
PR addresses this dataloader; already in the main repo
